version: "3.3"
services:
  fastapi:
    image: datascientest/fastapi:1.0.0
    #command: tail -F anything
    container_name: fastapi
    stdin_open: true
    tty: true
    networks:
      - network_api
    volumes:
      - ~/docker_exam:/home/my_tests
    ports:
      - "8000:8000"
    environment:
      - LOG= "1"
      - TEST_FILE= "test_authent.py"
  test_authent:
    depends_on: 
      - fastapi
    command: tail -F anything
    image: image_test_python_fastapi
    container_name: test_authent_container
    stdin_open: true
    tty: true
    networks:
      - network_api
    volumes:
      - ~/docker_exam:/home/my_tests
    environment:
      - LOG= "1"
      - TEST_FILE= "test_authent.py"
networks:
 network_api:
